### ISSUE TITLE
Can't sync orientation of view object

### ISSUE THREAD

**Issue by kain88-de** [conda-forge/nglview-feedstock#1]
The current version if broken if installed via conda-forge. I can't access the orientation of a view object. To reproduce use the following to create a new view

```python
import nglview as ng
import MDAnalysis as mda
from MDAnalysisTests.datafiles import PSF, DCD

u = mda.Universe(PSF, DCD)
view = ng.show_mdanalysis(u)
view._set_sync_camera()
```

now rotate the protein. `view.orientation` should now return a 3x3 matrix with the orientation. This might be due to using the new ipywidgets. The official package on bioconda still uses ipywidgets 5.x

**Comment by hainm** [comment]
> The official package on bioconda still uses ipywidgets 5.x

yeah, that's my intention.

**Comment by marscher** [comment]
On 22.03.2017 03:54, Hai Nguyen wrote:
>     The official package on bioconda still uses ipywidgets 5.x
>
> yeah, that's my intention.
Ok good to know. I thought you're already on ipywidgets 6 on your github 
master branch.

**Comment by marscher** [comment]
@hainm the bioconda recipe does not pin ipywidgets either. Probably this issue will first pop up, when ipywidgets will be updated on the defaults channel.

**Comment by hainm** [comment]
uhm, I am not sure why. I did explicitly request that here: https://github.com/bioconda/bioconda-recipes/blob/master/recipes/nglview/meta.yaml#L20-L24

**Comment by marscher** [comment]
sorry, my mistake! You're right.
