### ISSUE TITLE
post_link script fails 

### ISSUE THREAD

**Issue by jan-janssen** [conda-forge/nglview-feedstock#25]
```
ERROR conda.core.link:_execute(502): An error occurred while installing package 'conda-forge::nglview-1.1.9-py_0'.
LinkError: post-link script failed for package conda-forge::nglview-1.1.9-py_0
running your command again with `-v` will provide additional information
location of failed script: /srv/conda/bin/.nglview-post-link.sh
==> script messages <==
<None>

Attempting to roll back.
```

**Comment by hainm** [comment]
> running your command again with `-v` will provide additional information

Can you please try this?

**Comment by jan-janssen** [comment]
Hi @hainm, I am sorry for my delay. I figured out that it works fine if I remove nglview from my `environment.yml` file and install it during the `postBuild` phase: 
https://github.com/pyiron/pyiron/commit/103953692b49259f31620ac536c87b1634dde675
Most likely this is a general issue how anaconda is handling dependencies during installation.

**Comment by marscher** [comment]
If post linkage scripts fails, we can not ensure that the js extensions are enabled!

**Comment by marscher** [comment]
I think we should move the activation to a build script and depend on nbextensions during build phase.
