### ISSUE TITLE
remove package from conda-forge

### ISSUE THREAD

**Issue by kain88-de** [conda-forge/nglview-feedstock#3]
The original author likes to publish the package on bioconda. Since bioconda now depends largely on conda-forge it's impossible to use bioconda without conda-forge.  Conda now by default also prefers channel precedence (order in condarc) over package version when it's decide which package version to install. This is a problem for people who want to use bioconda as a backup channel for a few packages that aren't available in conda-forge.  For me this leads to regularly downgrading nglviewer when I update because conda wants to use nglviewer from conda-forge.

**Comment by marscher** [comment]
Is copying the bioconda package over to conda-forge a valid solution or
shall we delete this feedstock?
I'd prefer the copying solution, because we have software that depends
on nglview on conda-forge, but we do not want to force the users to add
bioconda.

**Comment by kain88-de** [comment]
@hainm I think you mentioned once that you had problems with conda-forge also making the latest version available

**Comment by marscher** [comment]
@gph82 fyi

**Comment by hainm** [comment]
>  I think you mentioned once that you had problems with conda-forge also making the latest version available

Yes, bioconda will check if there is a equal (or greater) version of nglview in conda-forge first. This will prevent updating `nglview` meta data (e.g: ipywidgets version). There is no strong reason to switch over `conda-forge`.

You can always tell user to 
`conda install nglview -c bioconda` first. (vs we (nglview) need to tell: please replace "bioconda" channel as you have been using to "conda-forge").

**Comment by marscher** [comment]
we agreed upon releasing nglview here only after it has been released on bioconda to avoid the build pipeline problems on biocondas side (see discussion here /github.com/arose/nglview/issues/712)
