### ISSUE TITLE
upcoming release does not have --conda for setup.py

### ISSUE THREAD

**Issue by marscher** [conda-forge/nglview-feedstock#47]
This is just an reminder for the future to remove the --conda option in the pip invocation here:

https://github.com/conda-forge/nglview-feedstock/blob/c8d45ded6bff91920f9ba6feb568b07cdf74ef1f/recipe/meta.yaml#L16

**Comment by ericpre** [comment]
Also see #48 for more simplification.

**Comment by hainm** [comment]
Updated in #48
