### ISSUE TITLE
noarch package does not work

### ISSUE THREAD

**Issue by jochym** [conda-forge/nglview-feedstock#5]
There is no display widget showing. At the same time bioconda package of the same version works fine. Please reconsider the move to noarch or look into this issue - it is probably a show-stopper for many.

**Comment by marscher** [comment]
@gph82 can you confirm this?

**Comment by jasongrout** [comment]
As mentioned in https://github.com/conda-forge/ipywidgets-feedstock/issues/31 (and as we found out the hard way with widgetsnbextension), noarch packages do not work with post-link scripts. If you want the javascript installed, change the package back to arch-specific and your post-link scripts should start working again.

**Comment by jochym** [comment]
Can we switch the feedstock back to working variant @marscher ?

**Comment by marscher** [comment]
thank you Jason for pointing this out.

**Comment by marscher** [comment]
@jochym can you please confirm that this now works for you?

**Comment by jochym** [comment]
Yes. It does. No objections to closing the issue.

**Comment by gph82** [comment]
Thanks @marscher for taking care of this

**Comment by marscher** [comment]
thanks for testing!
